### ISSUE TITLE
Zero Division Error in adjAGExposure

### ISSUE THREAD

**Issue by storcium** [kenneth-sturrock/PySkyX_ks#2]
I am running into a problem when trying to run guiding, but it's cloudy.  I am guessing the AG Brightness: 0.0 is the problem?

[02:46:48] Selected a guide star [0] at: 32.71, 51.72
     NOTE: Measuring AG exposure.
     NOTE: AG Brightness: 0.0
Traceback (most recent call last):
  File "C:\Users\Alex\pysky\run-all.py", line 312, in <module>
    if goImage(run_target,imgmode) != "Success":
  File "C:\Users\Alex\pysky\run-all.py", line 169, in goImage
    if goGuide() != "Success":
  File "C:\Users\Alex\pysky\run-all.py", line 90, in goGuide
    expRecommends = adjAGExposure(guiderExposure, guiderDelay, XCoord, YCoord)
  File "C:\Users\Alex\pysky\library\PySkyX_ks.py", line 106, in adjAGExposure
    newExp = 0.3 / units
ZeroDivisionError: float division by zero

**Comment by jvickroy** [comment]
Disclaimer: I'm just an interested lurker and not even a user of this software.

I just looked at the code (as perhaps you also did) and verified your suspicion.  If **brightness** is zero, **units** will also be zero hence the error.

**brightness**, in turn, is the ratio of brightest pixel value and full-well capacity.

It may be that the brightest pixel value was zero.  Unfortunately, I do not have a level of understanding to go beyond this.

**Comment by storcium** [comment]
Thanks, I am going to try the following tonight.  In the library code, I added on line 80:

        if (brightness == 0):
            # We have a problem, which would result in division by zero in e.g. line 160
            writeError("Brightess is zero, signal error")
            return "0,0" # Measure this in return and fail

and in my own function, I will then do this:

    expRecommends = adjAGExposure(guiderExposure, guiderDelay, XCoord, YCoord)
    if (expRecommends == "0,0"):
        writeNote("Error measuring brightness, it must be cloudy")
        return "Fail"

We'll see how this goes in the real world :)

**Comment by storcium** [comment]
Yes, caught this exact thing in the morning, and did not crash.  Not sure how Ken would like to handle this, but my hack is at least allowing the program to continue (and take flats etc)

[05:51:21] Selected a guide star [20] at: 79.98, 140.29
     NOTE: Measuring AG exposure.
     NOTE: AG Brightness: 0.0
    ERROR: Brightess is zero, signal error
     NOTE: Error measuring brightness, it must be cloudy
Guiding UNSUCCESSFUL

**Comment by kenneth-sturrock** [comment]
Thanks for flagging this issue.  Sorry it took me a while to notice this - I detest GitHub, so I seldom check in here.

Assuming that the original exposure was not zero then, yeah, the AG brightness being zero would be an problem. What surprises me is that you got an ADU value so low as to cause this. Oh well - I guess that's the joy of writing software. Unfortunately, another confounder is if the full well value (pulled from the FITS header BITPIX keyword) is odd - but that should be handled.

Obviously, you're running code different from mine but the exposure adjustment routine wouldn't normally get called and handed a light source unless there was something there (maybe noise?) to measure. So, it's hard for me to think through the big picture of what would cause this.

I'd like to "Fail" it like you did, but that gets ugly within run_target-2. A cloud wait goes into some really wrapped-up spaghetti code. If it's a cloud then the appropriate thing would be to wait. If it was a ridiculously dim star then the appropriate thing would be to bump up the exposure - but that was the exposure that found the light source in the first place.

So, at least for now, I'm taking the easy way out and set an abnormally low brightness to a 0.1 floor. That might just kick the can down the road and might result in a saturated star but I'm not sure what else to really do. I'll also tack an error flag into the return value so that an astute programming could at least get a warning.

I'm also going to update the return statement to a proper list instead of a string with delimiters.

Now I have to go test it though...

**Comment by kenneth-sturrock** [comment]
OK. I implemented the changes above and they seem to work based on the testing which I could perform.
